### ISSUE TITLE
Rewrite reproduction workflow to use Docker

### ISSUE THREAD

**Issue by gabrielskoglund** [chains-project/breaking-updates#33]
We want to store the reproduction of each breaking update in a format that will keep it reproducible in the long term. The best choice for this seems to be to commit it as a docker image with all dependencies downloaded. For this reason, propose the following workflow:

* Create a base docker image for a breaking update consisting of the cloned git repo.
* Using this image, run the four steps: compilation and tests before and after updating the dependency.
* Log the result in the following way:
  - Store the maven log 
  - Add reproduction information to the breaking update JSON
  - _If reproduction is successful:_ copy the jar files for both dependency versions from the docker containers. This means that we can analyze these jars in a later stage.
  - _If reproduction is successful:_ commit the container that reproduced the failing behavior and push it to a remote repository.

A basic version of this procedure is available in [this branch](https://github.com/chains-project/breaking-updates/tree/reproduction-rewrite). It captures most of the requirements above but does not push any containers. Furthermore it only processes one single breaking update at a time at present. Ideally we should parallelize this, running multiple docker images concurrently.

**Comment by monperrus** [comment]
merged to main! thanks @gabrielskoglund for the initial work and @frankreyesgarcia and @yogyagamage for the rest :+1:
