### ISSUE TITLE
debloat docker images

### ISSUE THREAD

**Issue by monperrus** [chains-project/breaking-updates#78]
docker images should be less than 500 MB.

we will measure and report in the paper the following size on disk:

* the size of the application after clone
* size of all dependencies (size of .m2)

**Comment by javierron** [comment]
smaller base image

https://hub.docker.com/layers/library/maven/3.9.2-eclipse-temurin-11-alpine/images/sha256-4e8b4313226bbf303948c3c098dbb1f952ec88696f9d0ba8b1c63b819530f12a?context=explore

**Comment by javierron** [comment]
To reduce size, you can checkout to target commit, then remove the `.git` directory
